// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: contest_teams.sql

package database

import (
	"context"
)

const deleteAllContestTeams = `-- name: DeleteAllContestTeams :exec
DELETE FROM contest_teams WHERE contest_id = $1
`

func (q *Queries) DeleteAllContestTeams(ctx context.Context, contestID int32) error {
	_, err := q.db.Exec(ctx, deleteAllContestTeams, contestID)
	return err
}

type InsertContestTeamsParams struct {
	ContestID int32 `json:"contest_id"`
	TeamID    int32 `json:"team_id"`
}
