// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForInsertContestTeams implements pgx.CopyFromSource.
type iteratorForInsertContestTeams struct {
	rows                 []InsertContestTeamsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertContestTeams) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertContestTeams) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ContestID,
		r.rows[0].TeamID,
	}, nil
}

func (r iteratorForInsertContestTeams) Err() error {
	return nil
}

func (q *Queries) InsertContestTeams(ctx context.Context, arg []InsertContestTeamsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"contest_teams"}, []string{"contest_id", "team_id"}, &iteratorForInsertContestTeams{rows: arg})
}
