// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/LuukBlankenstijn/fogistration/internal/shared/database/models"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSecret struct {
	UserID       int64              `json:"user_id"`
	PasswordHash string             `json:"password_hash"`
	Salt         string             `json:"salt"`
	CreatedAt    pgtype.Timestamptz `hash:"exclude" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `hash:"exclude" json:"updated_at"`
}

type Client struct {
	ID          int32            `json:"id"`
	Ip          string           `json:"ip"`
	LastSeen    pgtype.Timestamp `json:"last_seen"`
	CreatedAt   pgtype.Timestamp `hash:"exclude" json:"created_at"`
	PendingSync bool             `json:"pending_sync"`
}

type Contest struct {
	ID         int32            `json:"id"`
	ExternalID string           `json:"external_id"`
	FormalName string           `json:"formal_name"`
	StartTime  pgtype.Timestamp `json:"start_time"`
	EndTime    pgtype.Timestamp `json:"end_time"`
	CreatedAt  pgtype.Timestamp `hash:"exclude" json:"created_at"`
	UpdatedAt  pgtype.Timestamp `hash:"exclude" json:"updated_at"`
	Hash       string           `hash:"exclude" json:"hash"`
}

type ContestTeam struct {
	ContestID int32 `json:"contest_id"`
	TeamID    int32 `json:"team_id"`
}

type MessageQueue struct {
	ID          int32            `json:"id"`
	CommandType string           `json:"command_type"`
	Payload     []byte           `json:"payload"`
	CreatedAt   pgtype.Timestamp `hash:"exclude" json:"created_at"`
}

type Team struct {
	ID          int32            `json:"id"`
	ExternalID  string           `json:"external_id"`
	Name        string           `json:"name"`
	DisplayName pgtype.Text      `json:"display_name"`
	Ip          pgtype.Text      `json:"ip"`
	CreatedAt   pgtype.Timestamp `hash:"exclude" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `hash:"exclude" json:"updated_at"`
	Hash        string           `hash:"exclude" json:"hash"`
}

type User struct {
	ID          int64              `json:"id"`
	Username    string             `json:"username"`
	Email       string             `json:"email"`
	Role        models.UserRole    `json:"role"`
	ExternalID  pgtype.Text        `json:"external_id"`
	CreatedAt   pgtype.Timestamptz `hash:"exclude" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `hash:"exclude" json:"updated_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

type Wallpaper struct {
	ID        int32                   `json:"id"`
	Filename  pgtype.Text             `json:"filename"`
	Layout    *models.WallpaperLayout `json:"layout"`
	CreatedAt pgtype.Timestamptz      `hash:"exclude" json:"created_at"`
	UpdatedAt pgtype.Timestamptz      `hash:"exclude" json:"updated_at"`
}
