// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Client struct {
	ID        int32
	Ip        string
	LastSeen  pgtype.Timestamp
	CreatedAt pgtype.Timestamp `hash:"exclude"`
}

type Contest struct {
	ID         int32
	ExternalID string
	FormalName string
	StartTime  pgtype.Timestamp
	EndTime    pgtype.Timestamp
	CreatedAt  pgtype.Timestamp `hash:"exclude"`
	UpdatedAt  pgtype.Timestamp `hash:"exclude"`
	Hash       string           `hash:"exclude"`
}

type ContestTeam struct {
	ContestID int32
	TeamID    int32
}

type MessageQueue struct {
	ID          int32
	CommandType string
	Payload     []byte
	CreatedAt   pgtype.Timestamp `hash:"exclude"`
}

type Team struct {
	ID          int32
	ExternalID  string
	Name        string
	DisplayName pgtype.Text
	Ip          pgtype.Text
	CreatedAt   pgtype.Timestamp `hash:"exclude"`
	UpdatedAt   pgtype.Timestamp `hash:"exclude"`
	Hash        string           `hash:"exclude"`
}

type User struct {
	ID        string
	Name      string
	TeamID    pgtype.Int4
	Ip        pgtype.Text
	CreatedAt pgtype.Timestamp `hash:"exclude"`
	UpdatedAt pgtype.Timestamp `hash:"exclude"`
	Hash      string           `hash:"exclude"`
}
