name: fogistration
services:
  http:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/app
      - wallpapers:/wallpapers
    entrypoint: ["air", "-c", ".air-http.toml"]

  grpc:
    build: .
    ports:
      - "9090:9090"
    volumes:
      - .:/app
      - wallpapers:/wallpapers
    entrypoint: ["air", "-c", ".air-grpc.toml"]

  cmd-handler:
    build: .
    volumes:
      - .:/app
    entrypoint: ["air", "-c", ".air-cmdhandler.toml"]
    extra_hosts:
      - "host.docker.internal:host-gateway"


  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fogistration
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data:
  wallpapers:

