name: Release image (cmdhandler)

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_BASE: ${{ github.repository }}
  TARGET: cmdhandler
  IMAGE_SUFFIX: cmdhandler

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push ${{ env.TARGET }}
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          target: ${{ env.TARGET }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}-${{ env.IMAGE_SUFFIX }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}-${{ env.IMAGE_SUFFIX }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install cosign
        uses: sigstore/cosign-installer@v3
      - name: Cosign sign
        env:
          DIGEST: ${{ steps.build.outputs.digest }}
          IMAGE1: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}-${{ env.IMAGE_SUFFIX }}:${{ github.ref_name }}
          IMAGE2: ${{ env.REGISTRY }}/${{ env.IMAGE_BASE }}-${{ env.IMAGE_SUFFIX }}:latest
        run: |
          cosign sign --yes "${IMAGE1}@${DIGEST}"
          cosign sign --yes "${IMAGE2}@${DIGEST}"
