name: Release

on:
  push:
    tags: ['v*']
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Build binary
        env:
          CGO_ENABLED: 0
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o dist/fogistrationctl ./cmd/client/main.go
          (cd dist && sha256sum fogistrationctl > fogistrationctl_linux_amd64.sha256)

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: go/dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
