name: Build & Publish all images

on:
  release:
    types: [published]
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1               # build sequentially to reuse layers
      matrix:
        include:
          - target: http-server
            suffix: http-server
          - target: grpc
            suffix: grpc
          - target: cmdhandler
            suffix: cmdhandler

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Downcase repo for GHCR tags
        shell: bash
        run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (${{ matrix.target }})
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          target: ${{ matrix.target }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_LC }}-${{ matrix.suffix }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ env.REPO_LC }}-${{ matrix.suffix }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.version=${{ github.ref_name }}
            org.opencontainers.image.revision=${{ github.sha }}
